-- 코드를 입력하세요
SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO AS I
LEFT JOIN 
(SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE FROM REST_REVIEW 
GROUP BY REST_ID) AS R
ON I.REST_ID = R.REST_ID
WHERE ADDRESS LIKE '서울%' AND SCORE IS NOT NULL
ORDER BY SCORE DESC, FAVORITES DESC